// src/app/shared/components/cards/sections/archive/20241109/financials-section/financials-section.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardField, CardSection } from '../../../../../models';
import { LucideIconsModule } from '../../../../icons/lucide-icons.module';

type FinancialField = CardField & {
  change?: number;
  trend?: 'up' | 'down' | 'stable';
  format?: string;
};

interface FinancialFieldInteraction {
  field: FinancialField;
  metadata?: Record<string, unknown>;
}

@Component({
  selector: 'app-financials-section',
  standalone: true,
  imports: [CommonModule, LucideIconsModule],
  templateUrl: './financials-section.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FinancialsSectionComponent {
  @Input({ required: true }) section!: CardSection;
  @Output() fieldInteraction = new EventEmitter<FinancialFieldInteraction>();

  get fields(): FinancialField[] {
    return (this.section.fields as FinancialField[]) ?? [];
  }

  onFieldClick(field: FinancialField): void {
    this.fieldInteraction.emit({
      field,
      metadata: {
        sectionId: this.section.id
      }
    });
  }

  getTrendIcon(field: FinancialField): string | null {
    switch (field.trend) {
      case 'up':
        return 'trending-up';
      case 'down':
        return 'trending-down';
      case 'stable':
        return 'minus';
      default:
        return null;
    }
  }

  getChangeClass(field: FinancialField): string {
    if (field.change === undefined || field.change === null) {
      return 'text-muted-foreground';
    }
    if (field.change > 0) {
      return 'text-emerald-400';
    }
    if (field.change < 0) {
      return 'text-rose-400';
    }
    return 'text-amber-400';
  }
}

<div class="flex flex-col space-y-4">
  <div class="flex items-center justify-between pb-2">
    <h3 class="text-xl font-semibold text-foreground">{{ section.title }}</h3>
    <span *ngIf="fields.length" class="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-xs text-emerald-400">
      Financials
    </span>
  </div>

  <div class="grid gap-3">
    <button
      *ngFor="let field of fields"
      type="button"
      class="flex items-center justify-between rounded-2xl border border-border/40 bg-card/70 p-4 text-left transition-colors duration-300 hover:border-primary/40 hover:bg-card"
      (click)="onFieldClick(field)"
    >
      <div class="flex-1">
        <span class="text-sm text-muted-foreground">{{ field.label }}</span>
        <div class="mt-1 flex items-center gap-2 text-base font-semibold text-foreground">
          <ng-container [ngSwitch]="field.format">
            <span *ngSwitchCase="'currency'" class="flex items-center gap-1 text-emerald-400">
              <lucide-icon name="dollar-sign" size="16"></lucide-icon>
              {{ field.value }}
            </span>
            <span *ngSwitchDefault>{{ field.value }}</span>
          </ng-container>
          <lucide-icon
            *ngIf="getTrendIcon(field) as trendIcon"
            [name]="trendIcon"
            size="16"
            [ngClass]="getChangeClass(field)"
          ></lucide-icon>
        </div>
      </div>
      <div *ngIf="field.change !== undefined" class="text-right text-sm font-medium" [ngClass]="getChangeClass(field)">
        {{ field.change > 0 ? '+' : '' }}{{ field.change }}%
      </div>
    </button>
  </div>

  <div *ngIf="!fields.length" class="rounded-2xl border border-dashed border-border/50 bg-background/50 p-8 text-center text-muted-foreground">
    <lucide-icon name="dollar-sign" size="32" class="mx-auto mb-3 opacity-60"></lucide-icon>
    <p>No financial metrics available.</p>
  </div>
</div>

// Orange Sales Intelligence Cards System 5/src/components/sections/FinancialsSection.tsx
import React from 'react';
import { AISectionConfig, FinancialField } from '../../types';
import { TrendingUp, TrendingDown, Minus, DollarSign } from 'lucide-react';

interface FinancialsSectionProps {
  section: AISectionConfig;
  onFieldInteraction?: (data: any) => void;
}

export const FinancialsSection: React.FC<FinancialsSectionProps> = ({
  section,
  onFieldInteraction
}) => {
  const fields = section.fields as FinancialField[] || [];

  const getTrendIcon = (trend?: string) => {
    switch (trend) {
      case 'up':
        return <TrendingUp className="w-4 h-4 text-green-400" />;
      case 'down':
        return <TrendingDown className="w-4 h-4 text-red-400" />;
      case 'stable':
        return <Minus className="w-4 h-4 text-yellow-400" />;
      default:
        return null;
    }
  };

  const formatValue = (value: string, format?: string) => {
    if (format === 'currency') {
      return (
        <div className="flex items-center gap-1">
          <DollarSign className="w-4 h-4 text-green-400" />
          {value}
        </div>
      );
    }
    return value;
  };

  const handleFieldClick = (field: FinancialField) => {
    onFieldInteraction?.({
      sectionId: section.id,
      fieldId: field.id,
      action: 'click',
      value: field.value
    });
  };

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-medium text-foreground border-b border-border pb-2">
        {section.title}
      </h3>
      
      <div className="grid gap-3">
        {fields.map((field) => (
          <div
            key={field.id}
            className="flex justify-between items-center p-4 rounded-lg bg-card/50 border border-border/50 hover:bg-card/70 transition-colors cursor-pointer"
            onClick={() => handleFieldClick(field)}
          >
            <div className="flex-1">
              <span className="text-sm text-muted-foreground">
                {field.label}
              </span>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-base font-medium text-foreground">
                  {formatValue(field.value, field.format)}
                </span>
                {field.trend && getTrendIcon(field.trend)}
              </div>
            </div>
            
            {field.change !== undefined && (
              <div className="text-right">
                <span 
                  className={`text-sm font-medium ${
                    field.change > 0 ? 'text-green-400' : 
                    field.change < 0 ? 'text-red-400' : 'text-yellow-400'
                  }`}
                >
                  {field.change > 0 ? '+' : ''}{field.change}%
                </span>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
